"""Add source_url to news

Revision ID: 0f27468b03af
Revises: 2d6830652f54
Create Date: 2026-01-10 16:23:43.496081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f27468b03af'
down_revision: Union[str, Sequence[str], None] = '2d6830652f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'source_url')
    # ### end Alembic commands ###
