"""Add highlights_url to matches

Revision ID: 2d6830652f54
Revises: 682293f1ffea
Create Date: 2026-01-10 11:17:21.662897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6830652f54'
down_revision: Union[str, Sequence[str], None] = '682293f1ffea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('highlights_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'highlights_url')
    # ### end Alembic commands ###
