"""add name to email_signups

Revision ID: 56424a6e1e69
Revises: d360b844b85d
Create Date: 2026-01-04 02:18:41.741059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56424a6e1e69'
down_revision: Union[str, Sequence[str], None] = 'd360b844b85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_signups', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_signups', 'name')
    # ### end Alembic commands ###
