"""add news table properly

Revision ID: 682293f1ffea
Revises: ce33a16a340c
Create Date: 2026-01-10 01:38:37.101135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682293f1ffea'
down_revision: Union[str, Sequence[str], None] = 'ce33a16a340c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('story_type', sa.String(), nullable=True),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_match_id'), 'news_articles', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_match_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
