"""create email_signups table

Revision ID: d360b844b85d
Revises: baea7cc80975
Create Date: 2026-01-03 13:32:43.929757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd360b844b85d'
down_revision: Union[str, Sequence[str], None] = 'baea7cc80975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_signups_email'), 'email_signups', ['email'], unique=True)
    op.create_index(op.f('ix_email_signups_id'), 'email_signups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_signups_id'), table_name='email_signups')
    op.drop_index(op.f('ix_email_signups_email'), table_name='email_signups')
    op.drop_table('email_signups')
    # ### end Alembic commands ###
